apiVersion: v1
kind: blog-container
metadata:
  name: blog-container
  labels:
    name: blog-container
spec:
  containers:
    - name: blog-container
      image: testazurecontaineregistry.azurecr.io/testazurecontaineregistry:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
